### ISSUE TITLE
unable to install via composer

### ISSUE THREAD

**Issue by oceanwap** [dercoder/omnipay-paysafecard#1]
## throws error. using in laravel 5.1

our requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dercoder/omnipay-paysafecard could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

**Comment by dercoder** [comment]
Did you edit your "minimum-stability" setting?
