### ISSUE TITLE
Add Support for Notify

### ISSUE THREAD

**Issue by MHaendel** [dercoder/omnipay-paysafecard#2]
Could someone please add it, as its a required by paysafecard.

**Comment by dercoder** [comment]
Please explain this "function"

**Comment by MHaendel** [comment]
Paysafecards sends a callback to the okUrl, it should execute getSerialNumbers and if it aint captured, executeDebit. This gateway is missing support, due to the lack of support of callbacks by omnipay until recently.

**Comment by dercoder** [comment]
Use "completePurchase" also for okUrl. This should work.
