### ISSUE TITLE
Stability and feature complete?

### ISSUE THREAD

**Issue by StephenOTT** [dercoder/omnipay-paysafecard#3]
Hey

Whats the stability and feature set of the driver?

Things that were never implemented?
Things that were buggy during implementation?

Anything to watch out for or know?

**Comment by dercoder** [comment]
Hi,

since last week we use it in production. Currently its working fine.
Maybe i will change it to "stable" in the next few weeks.

The main features are implemented. Please tell me if you miss something.

**Comment by StephenOTT** [comment]
thanks
