### ISSUE TITLE
SOAP API vs Rest API

### ISSUE THREAD

**Issue by stefanhuber** [dercoder/omnipay-paysafecard#5]
Hi,
I must admit that I haven't tried the module yet, however I cannot find any information on the Paysafecard website about the SOAP API.

I am not sure, if the SOAP API is still supported, however is there any plan to update the repo for the Rest API in the near future?

**Comment by dercoder** [comment]
Hi,

this SOAP API should still work because we use it in production. I think the REST API is new. 
Do you think its recommend to switch to REST? 

Here are the SOAP Docs:
https://drive.google.com/file/d/0B18JlcgjKu2rckdPOVVPUHFqUFE/view?usp=sharing

**Comment by stefanhuber** [comment]
OK. Thanks for the Docs, I couldn't find any information about the SOAP API on the paysafecard website. Only information about the REST API is available: https://www.paysafecard.com/en/business/support/downloads/

Probably they only want to support one API in the longer term... However, as long as it still works one shouldn't care too much ;)

Thx

**Comment by dercoder** [comment]
I see. 
Please keep me up 2 date if you have any issues with SOAP.
Thx for your informations.

**Comment by stefanhuber** [comment]
Unfortunately there is no username/password available for the SOAP API (by default) only a REST API key. I contacted the support if there are still SOAP credentials.

**Comment by stefanhuber** [comment]
Ok. After contacting the support the SOAP API with username/password was activated. Also the docs are still there: https://www.paysafecard.com/en/business/support/downloads-soap/ however the link is not visible from the website...

**Comment by stefanhuber** [comment]
So far I can confirm everything works as expected with the SOAP API!

**Comment by dercoder** [comment]
Great :)
